### ISSUE TITLE
Timeline view issue with metric+celsius profile

### ISSUE THREAD

**Issue by Tiralavia** [rlightner/public-BrewStatus#11]
Using metric+celsius profile settings, timeline view entries are displayed in fahrenheit. 
![image](https://cloud.githubusercontent.com/assets/25282844/22755217/81f1d994-ee42-11e6-96a1-62e9d9056a99.png)

...while the fermentation charts display temperature values in celsius.

![image](https://cloud.githubusercontent.com/assets/25282844/22755296/dbb7f62a-ee42-11e6-9661-5a7ab429965b.png)

**Comment by ghost** [comment]
+1 came here to report the same issue.

**Comment by chrisolver** [comment]
+1 also to report this.

**Comment by rlightner** [comment]
I've just pushed out an update that should fix this issue. Please check as I can't test all timezones :)

**Comment by ghost** [comment]
Fixed for me, thanks!

**Comment by Tiralavia** [comment]
Fixed, works great at timezone UTC +01:00.

Thanks!!!
