### ISSUE TITLE
Recipes hop additions issue with metric system

### ISSUE THREAD

**Issue by Tiralavia** [rlightner/public-BrewStatus#12]
Using metric system within the range from 19 to 600 litres ( 5 to 160 gallons), hop additions are usually displayed in grams. It would be better to visualize hop attitions in grams, otherwise 3 more decimal digits are needed in order to have the correct recipe shown in Kg. You can find here below an abstract of BeerXML file hop section in metric system.

```
<HOP>
 <NAME>Motueka</NAME>
 <VERSION>1</VERSION>
 <ORIGIN>New Zealand</ORIGIN>
 <ALPHA>7.2000000</ALPHA>
 <AMOUNT>0.0543478</AMOUNT>
 <USE>Aroma</USE>
 <TIME>0.0000000</TIME>
 <NOTES>Flexible hop developed from Saaz.  Has notable character and aroma, balanced bitterness, and unique flavor.  
Used for: Lagers, Belgian Ales and Bohemian Pilsner.  
Substitutes: Saaz</NOTES>
 <TYPE>Aroma</TYPE>
 <FORM>Pellet</FORM>
 <BETA>5.2500000</BETA>
 <HSI>15.0000000</HSI>
 <DISPLAY_AMOUNT>54.35 g</DISPLAY_AMOUNT>
 <INVENTORY>85.00 g</INVENTORY>
 <DISPLAY_TIME>0.0 min</DISPLAY_TIME>
</HOP>    
```

**Comment by rlightner** [comment]
I'm in the midst of rewriting the recipe import and display. I'll be including this type of info for sure. Thanks!

**Comment by rlightner** [comment]
This should be fixed.
