### ISSUE TITLE
No data showing

### ISSUE THREAD

**Issue by finkdiff** [rlightner/public-BrewStatus#14]
My Tilt appears to be working fine and when entering the cloud URL i get the following:

{"result":"success":"row":1} 

However on the website I see nothing appear, any way to troubleshoot this? 

I have not uploaded a beer.xml but form the instructions this does not appear to be necessary and my software does not export to XML anyway.

**Comment by rlightner** [comment]
Sadly, the site requires you to upload a BeerXML at this time.

**Comment by finkdiff** [comment]
Thanks for getting back to me, is it possible to have an online form on the website to get the barebones information and generate a basic BeerXML from that (I am talking maybe even only name, OG and estimated FG)?

**Comment by jimpdx** [comment]
👍

**Comment by grinn** [comment]
@finkdiff, See #25.
