### ISSUE TITLE
Brew xlm ingredients: tsp vs oz

### ISSUE THREAD

**Issue by EmDubeu** [rlightner/public-BrewStatus#18]
In my brew xml file I show ingredients (irish moss, yeast nutrient) in tsp. When I import the xml file into brewstat.us, those ingredients show up as oz.

xml file:
![image](https://cloud.githubusercontent.com/assets/6434553/23136488/cbeae442-f751-11e6-848c-e0e54dbee58e.png)

Brewstat recipe:
![image](https://cloud.githubusercontent.com/assets/6434553/23136507/e6df0fb2-f751-11e6-87c7-ce39d534f44a.png)

**Comment by rlightner** [comment]
It's because the beer XML spec only signifies liquid or dry weight. The display text it an optional item that's added by beer smith and not offset of the spec. I'll be building that out when I release the recipe editor.

**Comment by EmDubeu** [comment]
I just noticed the BOIL_TIME in my XML is 90 (which is right), and the Boil Time in my brew for Brewstat.us shows 60 min.

**Comment by rlightner** [comment]
Email me your XML file?

**Comment by rlightner** [comment]
I've fixed the boil issue. Please let me know if this is still happening.
