### ISSUE TITLE
Notification Button - spelling

### ISSUE THREAD

**Issue by EmDubeu** [rlightner/public-BrewStatus#2]
The Add Notification button is incorrectly spelled "Notifcation".
![notifcation](https://cloud.githubusercontent.com/assets/6434553/19083221/22e724da-8a16-11e6-9f75-1076905cd4ad.PNG)

**Comment by EmDubeu** [comment]
Also appears incorrectly spelled when editing a notification.
![edit notifcaiton](https://cloud.githubusercontent.com/assets/6434553/19083268/58cfbfd0-8a16-11e6-908e-0e28c8c16c9a.PNG)

**Comment by EmDubeu** [comment]
![20161025_222705](https://cloud.githubusercontent.com/assets/6434553/19714435/f3a3506a-9b02-11e6-8136-35d65ba8f392.png)

Button still misspelled on Create New Notification section

**Comment by rlightner** [comment]
Clearly I should not be drinking my homebrew and closing issues!  This is now fixed and out.

**Comment by EmDubeu** [comment]
👌
