### ISSUE TITLE
Error 404 message when clicking on Tilt device from Dashboard

### ISSUE THREAD

**Issue by EmDubeu** [rlightner/public-BrewStatus#20]
I get an error 404 message when I click on the Tilt device from the status thread (right side of Dashboard).

My renaming the Tilt device may have caused this...

[Error 404.zip](https://github.com/rlightner/public-BrewStatus/files/792087/Error.404.zip)

**Comment by EmDubeu** [comment]
Also, if you change the nickname of the Tilt device in the Tilt Hydrometer settings page, the old name still shows as assigned on your brew on the Dashboard. After several clicks around the site, or maybe a certain amount of time passed, the newly renamed Tilt device now appears in the Brew on the Dashboard.

**Comment by rlightner** [comment]
Updated the urls to the correct ones.
