### ISSUE TITLE
Multiple devices uploading data

### ISSUE THREAD

**Issue by finkdiff** [rlightner/public-BrewStatus#23]
Does Brewstat support multiple devices uploading data for the same brew? I have the Tilt software on both my iPad and iPhone and together they would provide more data points than either one alone as I do not yet have a dedicated device picking up the beacon broadcasts.

**Comment by jimpdx** [comment]
@finkdiff based on my testing yes it will accept data from multiple devices

**Comment by rlightner** [comment]
Hi there, Right now BrewStat.us only supports one tilt per brew. The software updates every 15 min which provides pretty good resolution. Tell me about what you're trying to accomplish?

-Raine

**Comment by jimpdx** [comment]
(Sorry I was mistaken)

**Comment by rlightner** [comment]
Nothing wrong, you can have multiple tilt devices, but they just have to report to an individual brew.
