### ISSUE TITLE
Notifications doesn't trigger accordingly 

### ISSUE THREAD

**Issue by Zeppen** [rlightner/public-BrewStatus#27]
Hi there, I have a problem, I keep getting notifications about temperature higher than 20 celcius but the data says 18.3 in the log. What seems to be the problem?
See my screenshots here : https://imageshack.com/i/pnYmwZxUp and https://imageshack.com/i/pnDFQtdlp seems weird that it doesn't match 

It seems to me like the "trigger" does not work. I deleted my notification and set a new one to 22'C but I keep getting emails about temp higher than 22'C even though real temp according to the log is lower than 22'C.

**Comment by Zeppen** [comment]
One more thing, it doesn't seem to trigger the time schedule for notifications as I have set, it keeps on notifying every 15 minutes instead of the the set 1h intervall.

**Comment by rlightner** [comment]
Cleared the notification cache, let me know if this continues.

**Comment by Zeppen** [comment]
Hi there 
The notifications about the temperature came back :(

/Rickard 

Den 19 mars 2017 20:26, kI 20:26, Raine Lightner <notifications@github.com> skrev:
