### ISSUE TITLE
Display Brew Graph Times in clients time zone.

### ISSUE THREAD

**Issue by jultican024** [rlightner/public-BrewStatus#28]
I notice the raw data was uploaded in my time zone (PDT) but the graph shows it in UTC.  Could you calculate the offset for any client and show the graph in the users timezone?  (http://stackoverflow.com/questions/1091372/getting-the-clients-timezone-in-javascript might be a lead.)

**Comment by rlightner** [comment]
Yes, this is a known issue right now. I'll get a fix out for this sometime this week.

**Comment by rlightner** [comment]
I think this is now fixed, can you confirm?

**Comment by jultican024** [comment]
It does not look like it from my side. (Using a Chrome Browser)

My active fermentation with uploading tilt data - https://www.brewstat.us/brew/581/tailspin-tail-slip-brown

Graph shows last update at 17:00 and the tilt data shows 10:08am.

**Comment by elogicmedia** [comment]
It doesn't look updated for me yet either: https://www.brewstat.us/share/579/pale-ale-cascade-citra

The graph shows 18th April 16:00 and the last timestamp within the data listing is April 19, 4:51:12am (which is correct - I'm in Australia and work early)

Thanks

**Comment by rlightner** [comment]
Looks like I hadn't pushed the fix. It's out now as well. Please verify!

**Comment by jultican024** [comment]
Verified as fixed!  I now see my graph in my local time.

**Comment by rlightner** [comment]
#winning!

**Comment by elogicmedia** [comment]
It's not 100% right for me yet, want me to open another issue? It's closer though.

Latest Timestamp is April 19, 4:51:12 am, however, the latest graph plot is April 19, 2:00:00 am

I have 10 entries after 2:00 am today they haven't listed.

Thanks

**Comment by rlightner** [comment]
It groups the times in to buckets of 4 hours after a brew has been going for more than 3 days.
