### ISSUE TITLE
Brew Readings do not display in Internet Explorer 11

### ISSUE THREAD

**Issue by jultican024** [rlightner/public-BrewStatus#29]
The Brew Readings chart does not show up in IE 11. (https://www.brewstat.us/share/581/tailspin-tail-slip-brown)

Microsoft Windows [Version 10.0.14393]
IE 11: 11.953.14393.0
Java Version 8 Update 121

The chart seems to open fine in Chrome and Firefox.

**Comment by rlightner** [comment]
/me shakes a fist at IE 11

I'll see if I can figure out what is going on. Thanks!

**Comment by jultican024** [comment]
Haha - I don't blame you.  Web clients are a pain!  Let me know if you need a 'sucker' to validate any changes. :)

**Comment by rlightner** [comment]
I've updated the chart to fix the IE11 issue. Please verify!

**Comment by jultican024** [comment]
Verified as fixed!
