### ISSUE TITLE
Three decimal places needed on SG data

### ISSUE THREAD

**Issue by chastuck** [rlightner/public-BrewStatus#31]
When the specific gravity ends in zero only two decimal places are shown. i.e., 1.070 SG is shown as 1.07. Can this be changed please as it looks odd.

**Comment by elogicmedia** [comment]
Agreed. Thanks

**Comment by rlightner** [comment]
Where are you seeing this at?

**Comment by elogicmedia** [comment]
It seems to be everywhere, on the dashboard, on the details page, within the tilt data area etc. See sample screenshots below. 

![tilt1capture](https://user-images.githubusercontent.com/510943/29437980-3f5a0c82-83f7-11e7-8856-e2e8dae96fb5.JPG)

![tilt2capture](https://user-images.githubusercontent.com/510943/29437999-5e6b4dfc-83f7-11e7-9d54-fb83c53f244a.JPG)

Thanks

**Comment by rlightner** [comment]
Thanks, the 4 recipes I looked at I couldn't find an example!

**Comment by rlightner** [comment]
OK, released an update last night, I think that covers those areas. Reopen if you find any others.

**Comment by elogicmedia** [comment]
![tilt3capture](https://user-images.githubusercontent.com/510943/29498041-89dc4c42-8637-11e7-842f-53e742021d7c.JPG)

Another one on the dashboard.

Thanks
