### ISSUE TITLE
Multiple Yeast Strains

### ISSUE THREAD

**Issue by jimpdx** [rlightner/public-BrewStatus#37]
Does your architecture support more than one yeast entries per recipe?

**Comment by jimpdx** [comment]
Editing the title. I think this issue only applies when you upload a BeerXML file. That, or it does not recognize multiple yeast entries from the file generated by BeerSmith?

**Comment by rlightner** [comment]
The system can support it, but I only expose one yeast right now. I'll add it to the list of things to get out soon!

**Comment by rlightner** [comment]
With the latest update, if you upload a BeerXML file with more than one yeast, it should now display on the page.

**Comment by jimpdx** [comment]
Thanks!
