### ISSUE TITLE
Tilt Hydrometer Not Deleting

### ISSUE THREAD

**Issue by simplepleasuresbrewery** [rlightner/public-BrewStatus#38]
When I go to delete a Tilt Hydrometer when ticking the yes button for delete it is still there.

**Comment by simplepleasuresbrewery** [comment]
When I go to delete a Tilt Hydrometer when ticking the yes button for delete it is still there.

**Comment by rlightner** [comment]
Which tilt are you trying to delete, blue or black?

**Comment by simplepleasuresbrewery** [comment]
Was trying to delete both.

But all okay now as I understand one URL does both tilts. Where do I paste
the URL in the app.

Guess it will be Cloud URL? And I do this for both Tilt colors.

Sorry for the obvious questions.

Regards

Mark

**Comment by rlightner** [comment]
You'll only need to paste the Cloud URL in once. I think I've fixed the issue. Let me update the site and i'll verify.

**Comment by simplepleasuresbrewery** [comment]
Great

Regards

Mark

**Comment by rlightner** [comment]
OK, issue has been fixed. You'll need to add back the Tilts you removed.

**Comment by rlightner** [comment]
@simplepleasuresbrewery Did this work for you?

**Comment by simplepleasuresbrewery** [comment]
Yes they deleted and I added them back.

Regards

Mark
