### ISSUE TITLE
Multiple Instances of same recipe

### ISSUE THREAD

**Issue by merlinwerks** [rlightner/public-BrewStatus#41]
There are multiple entries for the last couple of brews I have done and I can't archive or hide them. Also is there any way we can simply delete rather than archive or hide?

**Comment by merlinwerks** [comment]
OK it appears to be fixed now. I also found where you can delete after hiding then viewing "hidden" brews.

**Comment by rlightner** [comment]
I think the original issue is a caching issue which I'll get fixed today. Why it's creating dupes, now, I don't know but will figure out.
