### ISSUE TITLE
Three Brews With Same Name

### ISSUE THREAD

**Issue by DukeHeart** [rlightner/public-BrewStatus#46]
Hi,

I have two brews that at some point had the same name. 
I am unable to hide or them or delete them.
I tried renaming them but they still will not hide or delete.

Mangrove Jack Apple Cider 5
Mangrove Jack Apple Cider 6

Cheers
Mark

**Comment by rlightner** [comment]
Are they still not deleting?

**Comment by DukeHeart** [comment]
Sorry for late reply. Finally got them deleted.
