### ISSUE TITLE
Temperature Unit on new graphs

### ISSUE THREAD

**Issue by DukeHeart** [rlightner/public-BrewStatus#48]
Hi,

The new graphs are great. 
However I can't find a way to get the temperature on the graphs to default to Celsius any more.
If I switch units to f and back to c (top right drop down) it works. However it is not saved for next
time I open the graph.

Cheers
Duke

**Comment by rlightner** [comment]
Sorry about that, this should be now fixed. I also made the menu reflect the different options that are under your profile. It currently won't hard save the options, its only for the duration of the page view.

**Comment by DukeHeart** [comment]
Cheers, thanks for the fast reply.
