### ISSUE TITLE
Cannot see older beer stats when I view

### ISSUE THREAD

**Issue by kellyho67** [rlightner/public-BrewStatus#49]
I have 3 beers now.. one old one I can see, the new one that just started logging I cannot see any details on the view screen and one I finished about a week ago I cannot see on the view details anymore.. Just a blank page when I view.

Here is one of the URL
https://www.brewstat.us/brew/2271/high-heel-imperial-ipa

**Comment by rlightner** [comment]
Taking a look, thanks!

**Comment by rlightner** [comment]
This is fixed now.
