### ISSUE TITLE
iOS Safari Dashboard Empty

### ISSUE THREAD

**Issue by kellyho67** [rlightner/public-BrewStatus#51]
when using Safari on iOS I'm getting a blank dashboard.. I have tested with an iOS Simulator as well as my phone iOS 10.3.3.

In a responsive view set in chome with the emulator on Mobile layout the Dashboard renders fine.

iOS Simulator shows only a blank dashboard also.
![cursor_and_glass_and_iphone_se_ _ios_10_3__14e8301_](https://user-images.githubusercontent.com/48510/32736455-be4d8964-c854-11e7-8ec7-e7cd70c34e5f.jpg)

**Comment by rlightner** [comment]
Fixed. Due to an issue with Webpack and Safari 10.3.3 / ES6

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/92

**Comment by kellyho67** [comment]
Very good.. I have not been hit by that bug yet on ES6 or my configs for webpack but good find!

**Comment by rlightner** [comment]
This is what I ended up having to use.
       
`new UglifyJsPlugin({
            parallel: true,
            sourceMap: true,
            uglifyOptions: {
                mangle: {
                    safari10: true
                },
                warnings: false
            }
        })`

**Comment by kellyho67** [comment]
Thanks for the info, I just placed it in my notes for my webpack config just in case!
