### ISSUE TITLE
Numbers displayed wrong on mobile version of site

### ISSUE THREAD

**Issue by foogod** [rlightner/public-BrewStatus#52]
I just started monitoring my first brew with my new Tilt and brewstat.us..  I noticed, however, that when viewed on my phone, the site is displaying a couple of things oddly or wrongly:

* Percent attenuation: Is showing up as "0.0989010989010978%".  There are two issues with this, the more important being that it's off by a factor of 100 (it should be around 10%, not 0.10%).  The other is, obviously, that it seems a little silly to be printing this value to 16 decimal places..)
* ABV: Shows up with an extra "%" (i.e. "1.36%%" instead of "1.36%")

Both of these values show up fine when looking at the desktop version of the site, it appears to be only the mobile version that's screwy..

**Comment by rlightner** [comment]
It's all about precision!  Clearly its a bug. I'll get a fix out for this asap.

**Comment by rlightner** [comment]
This has been fixed and released.

**Comment by foogod** [comment]
Thanks, BTW, about the quick response to this (meant to comment on that at the time)

I did confirm this appeared to be fixed last week.  Unfortunately, it looks like this change reverted sometime in the past few days, as now when I check the site on my phone it's back to its old (broken) behavior..
