### ISSUE TITLE
Relax requirements for Tilt nickname

### ISSUE THREAD

**Issue by foogod** [rlightner/public-BrewStatus#53]
When adding a new Tilt device, the site tells me that "Tilt nickname needs to be between 5 and 25 characters".  Why??

I don't understand why nickname is a required field to begin with, actually, since in general the color has to be unique, due to the way Tilts work, anyway (and I'm not particularly in the habit of giving my inanimate sensor devices cutesy names just for the heck of it).  Even if for some reason the nickname does have to be required, the minimum length of 5 characters seems completely arbitrary and annoying.  Why can't I nickname my red Tilt as "red"?  Or my blue one as "blue"?  Both of those names seem perfectly reasonable to me but are not allowed by the site for some reason..

**Comment by rlightner** [comment]
Valid enough point

**Comment by rlightner** [comment]
I've relaxed the requirement to between 1 and 25. This has been released.
