### ISSUE TITLE
Mash Temp

### ISSUE THREAD

**Issue by enobale** [rlightner/public-BrewStatus#59]
I imported a recipe yesterday and the Mash Temp is saying that it is 68 degrees Fahrenheit. It should be 154 degrees Fahrenheit. I looked at the XML file that I used to import the recipe and it's correct in the XML file, but something happened when it imported into brewstat. 

Here is the link to my recipe for reference. 

https://www.brewstat.us/brew/2952/stacy-brown-got-two-brown-ale

Aaron

**Comment by allisteinn** [comment]
Yeah, I have this issue as well, with Mash and Mash Out temperatures showing at 19°C and 25°C, which comes to 66°F and 77°F respectively. Seems that the mash temp is being parsed incorrectly as Fahrenheit instead of Celsius from the beerxml file.

**Comment by rlightner** [comment]
This should be fixed now.
