### ISSUE TITLE
Dashboard is not updating

### ISSUE THREAD

**Issue by ESDillenkofer** [rlightner/public-BrewStatus#64]
The dashboard is showing data from 2 days ago, yet the "view" option is showing current data.

![dashboard](https://user-images.githubusercontent.com/30899305/41411778-f77bfac8-6fab-11e8-839c-d2cfcece1947.JPG)
![view](https://user-images.githubusercontent.com/30899305/41411787-fc7af86c-6fab-11e8-99ef-81a824f8db36.JPG)

**Comment by brpeterso** [comment]
I'm having the same problem!  I came here to report the problem and it looks like you beat me to it.  The detailed view is updated while the main dashboard hasn't updated in a day or two.

![image](https://user-images.githubusercontent.com/24624605/41424870-3abeb2b4-6fcd-11e8-9d3c-70c6813ea6be.png)
![image](https://user-images.githubusercontent.com/24624605/41424909-4da3c2ac-6fcd-11e8-9e8b-df9d17e8c93c.png)

**Comment by rlightner** [comment]
Pushing out a fix right now. Got to aggressive with caching and not expiring the data when new data is submitted. Should be out in less than 5 mins.

**Comment by brpeterso** [comment]
The main dashboard is now up-to-date for me.  Thanks!  Appreciate the great work.

**Comment by ESDillenkofer** [comment]
Looks great, thanks for the quick fix!
