### ISSUE TITLE
Tilt Pi not reporting

### ISSUE THREAD

**Issue by buddapps** [rlightner/public-BrewStatus#68]
I have three devices that I have tried with your service:

1. iPhone with tilt app
2. Raspberry Pi with tilt pi software
3. Android galaxy tablet with tilt

All three devices see readings from the tilt and will log to the normal google spreadsheet data link for the tilt device.

In trying your service, I initially used the Tilt Pi solution and in watching it; it reports that it is establishing a cloud connection to the URL and then reports success on the status screen. 

However dashboard failed to report any activity. I then switched to the iPhone and did get an activity report however only two readings were recorded and it stopped updating.

**Comment by rlightner** [comment]
What is the id of the Brew you're reporting data to?

**Comment by buddapps** [comment]
Freds on your site. Will send URL when I get home. X

Sent from my iPhone

On Aug 13, 2018, at 5:14 PM, Raine Lightner <notifications@github.com<mailto:notifications@github.com>> wrote:


What is the id of the Brew you're reporting data to?

**Comment by buddapps** [comment]
Needed to visit the system menu and do an "UPDATE APP(FLOW)" to at least V2.1 in order to work with BrewStatus.

**Comment by rlightner** [comment]
Glad we were able to figure this one out!
