### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by tommyteck** [rlightner/public-BrewStatus#73]
I have been unable to login for a couple weeks 

I just get

Uh Oh! Something Really Bad Happened

Either we're really busy or you've discovered a bug in our software. We're sorry about that.

You can try again by refreshing the page.

I have waited weeks refreshed tried multiple browsers on multiple OS's on multiple platforms and still no luck

**Comment by rlightner** [comment]
Looks like your black tilt had sent some bad data. I've archived those readings (5 total). Can you try logging in again?

**Comment by tommyteck** [comment]
Awesome Thanks.  I shouldn’t have waited so long to report my issue.

 

I have several different things reporting I’m guessing one of them has an issue.

 

What field was the error in do you know?  I will put some checks in to prevent it.

 

Tilt Pi – not used but gets plugged in by mistake sometimes

Python script – Most used

Brewfather

Custom LUA app – Not used yet but plan on moving to this.

 

Thanks again

 

Tom

**Comment by rlightner** [comment]
No worries, sorry it took me so long to respond.  It was missing Temp/Gravity for 5 records on your black tilt.
