### ISSUE TITLE
Unable to add all tilt Hydrometers

### ISSUE THREAD

**Issue by cgrater** [rlightner/public-BrewStatus#76]
It seems there is a limit to the number of tilt devices that can be added.  It is possible to have 8 Tilt devices (1 per color) reporting, but after 5 are added to Brewstat, the "Add Tilt Device" button becomes greyed out and unclickable.

I currently have brews going that I cannot track in Brewstat because I have hit the apparent cap of 5 tilt devices.  Is there a way to update to allow tracking of all 8 Tilt colors simultaneously?

![image](https://user-images.githubusercontent.com/37853260/79854079-e8114380-8396-11ea-9efe-3cca1def55a3.png)

**Comment by rlightner** [comment]
I've bumped this to 10, please give it a try!

**Comment by cgrater** [comment]
Works perfectly!  Thanks!
