### ISSUE TITLE
Cannot login anymore (Facebook login)

### ISSUE THREAD

**Issue by OlafWinkel** [rlightner/public-BrewStatus#78]
I cannot login at Brewstat.us. I used to login via Facebook login, but it isn't working anymore.  The error is in Dutch: "App is nog in ontwikkeling: Deze app bevindt zich nog in ontwikkelingsmodus, waar je geen toegang toe hebt. Meld je aan als geregistreerde testgebruiker of vraag een app-beheerder om toestemming."

**Comment by rlightner** [comment]
This should be fixed now!

**Comment by OlafWinkel** [comment]
Yes, it is working. Tnx for the quick response
