### ISSUE TITLE
Red Tilt Brewometer not available

### ISSUE THREAD

**Issue by harliv** [rlightner/public-BrewStatus#9]
I am not seeing an option for the red brewometer. Can this be supported as well?

**Comment by rlightner** [comment]
Are you able to select the Device Color from the dropdown?

![image](https://cloud.githubusercontent.com/assets/354640/19494567/9e8759ba-9534-11e6-95e3-b61a3a271096.png)

**Comment by harliv** [comment]
On mine I have orange but not red. Here's a screenshot:

https://www.dropbox.com/s/bj025ut3wboow4b/Screenshot%202016-10-18%2013.14.38.png?dl=0

**Comment by rlightner** [comment]
Try scrolling if you can, I know there is now scroll bar present, but it should scroll with finger or mouse.

**Comment by harliv** [comment]
Ah sure enough! Embarrassed I didn't figure that out!

Thanks!
